name: CI

  # Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action'
        required: true
        type: choice
        options:
          - Run
          - No
    

env:
  DAY: Monday

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    if : github.event.inputs.action == 'Run'
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ steps.vars.outputs.workspace }}
      stage_env: ${{ steps.vars.outputs.stage_env }}
    steps:
      - name: Set variables
        id: vars
        run: |
          WORKSPACE=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            STAGE_ENV="production"
          elif [[ "${{ github.ref_name }}" == release/* ]]; then
            STAGE_ENV="staging"
          else
            STAGE_ENV="development"
          fi
          
          echo "workspace=$WORKSPACE" >> $GITHUB_OUTPUT
          echo "stage_env=$STAGE_ENV" >> $GITHUB_OUTPUT
          echo "workspace=$WORKSPACE"
          echo "stage_env=$STAGE_ENV"

  greeting_job:
    if : github.event.inputs.action == 'Run'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: "Say hello"
        run: echo ${{ env.DAY }}
